spring:
  application:
    name: order-manager
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

meilisearch:
  host: ${MEILISEARCH_HOST}
  port: ${MEILISEARCH_PORT}
  api-key: ${MEILISEARCH_API_KEY}
