services:
  order-manager:
    image: order-manager:0.1
    environment:
      DB_URL: jdbc:mariadb://db:3306/orders
      DB_USER: user
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      meilisearch:
        condition: service_healthy

  db:
    image: mariadb:11.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: orders
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis-custom:7.2.4
    ports:
      - "6379:6379"
    environment:
      REDIS_PORT: 6379
      ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  meilisearch:
    image: getmeili/meilisearch:v1.12
    volumes:
      - ./data.ms:/data.ms
    ports:
      - "7700:7700"
    healthcheck:
      test: [ "CMD", "curl", "-X", "GET", "http://127.0.0.1:7700/health" ]
      interval: 10s
      timeout: 5s
      retries: 5


